spring:
  application:
    name: qube-launcher
qubemc:
  repos:
    launcher-meta:
      url: launchermeta.mojang.com
      version-manifest:
        version: V2
    piston-meta:
      url: piston-meta.mojang.com
      version: V1